/* cdeps.c — thin C shell: embed Lua, register the native primitives Lua's
 * stdlib lacks (sha256 + a little filesystem), then run cdeps.lua (from disk in
 * dev mode, else the embedded bytecode). All real logic lives in cdeps.lua. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>

#include "lua.h"
#include "lauxlib.h"
#include "lualib.h"

#define SHA256_IMPLEMENTATION
#include "sha256.h"

/* The embedded precompiled cdeps.lua. Generated by the Makefile (luac + xxd).
 * Guarded so the file still compiles before the header has been generated. */
#if defined(__has_include)
#  if __has_include("cdeps_lua.h")
#    include "cdeps_lua.h"
#    define CDEPS_HAVE_BYTECODE 1
#  endif
#endif

/* --------------------------------------------------------------------------
 * Native filesystem helpers
 * ------------------------------------------------------------------------ */

static int mkdir_p(const char *path) {
    char tmp[4096];
    size_t len = strlen(path);
    if (len >= sizeof tmp) { errno = ENAMETOOLONG; return -1; }
    memcpy(tmp, path, len + 1);
    if (len && tmp[len - 1] == '/') tmp[len - 1] = '\0';
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            if (mkdir(tmp, 0777) != 0 && errno != EEXIST) return -1;
            *p = '/';
        }
    }
    if (mkdir(tmp, 0777) != 0 && errno != EEXIST) return -1;
    return 0;
}

/* Recursive delete, depth-first. */
static int rm_rf(const char *path) {
    struct stat st;
    if (lstat(path, &st) != 0) return errno == ENOENT ? 0 : -1;
    if (S_ISDIR(st.st_mode)) {
        DIR *d = opendir(path);
        if (!d) return -1;
        struct dirent *e;
        char child[4096];
        while ((e = readdir(d))) {
            if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, "..")) continue;
            snprintf(child, sizeof child, "%s/%s", path, e->d_name);
            rm_rf(child);
        }
        closedir(d);
        return rmdir(path);
    }
    return unlink(path);
}

static int copy_file_native(const char *src, const char *dst) {
    FILE *in = fopen(src, "rb");
    if (!in) return -1;
    FILE *out = fopen(dst, "wb");
    if (!out) { fclose(in); return -1; }
    char buf[65536];
    size_t n;
    int err = 0;
    while ((n = fread(buf, 1, sizeof buf, in)) > 0) {
        if (fwrite(buf, 1, n, out) != n) { err = 1; break; }
    }
    if (ferror(in)) err = 1;
    fclose(in);
    if (fclose(out) != 0) err = 1;
    if (!err) {
        struct stat st;
        if (stat(src, &st) == 0) chmod(dst, st.st_mode & 0777);
    }
    return err ? -1 : 0;
}

/* recursive walk collecting regular files relative to `base`, skipping .git */
static void walk_into(lua_State *L, const char *base, const char *rel, int *idx) {
    char full[4096];
    if (rel[0]) snprintf(full, sizeof full, "%s/%s", base, rel);
    else        snprintf(full, sizeof full, "%s", base);

    DIR *d = opendir(full);
    if (!d) return;
    struct dirent *e;
    while ((e = readdir(d))) {
        if (!strcmp(e->d_name, ".") || !strcmp(e->d_name, "..")) continue;
        if (!strcmp(e->d_name, ".git")) continue;
        char childrel[4096], childfull[4096];
        if (rel[0]) snprintf(childrel, sizeof childrel, "%s/%s", rel, e->d_name);
        else        snprintf(childrel, sizeof childrel, "%s", e->d_name);
        snprintf(childfull, sizeof childfull, "%s/%s", full, e->d_name);

        struct stat st;
        if (lstat(childfull, &st) != 0) continue;
        if (S_ISDIR(st.st_mode)) {
            walk_into(L, base, childrel, idx);
        } else if (S_ISREG(st.st_mode)) {
            lua_pushstring(L, childrel);
            lua_rawseti(L, -2, ++(*idx));
        }
    }
    closedir(d);
}

/* --------------------------------------------------------------------------
 * Lua bindings (module "cdeps_native")
 * ------------------------------------------------------------------------ */

static int l_sha256(lua_State *L) {
    const char *path = luaL_checkstring(L, 1);
    char hex[65];
    if (sha256_file(path, hex) != 0) { lua_pushnil(L); return 1; }
    lua_pushstring(L, hex);
    return 1;
}

static int l_exists(lua_State *L) {
    struct stat st;
    lua_pushboolean(L, stat(luaL_checkstring(L, 1), &st) == 0);
    return 1;
}

static int l_isdir(lua_State *L) {
    struct stat st;
    const char *p = luaL_checkstring(L, 1);
    lua_pushboolean(L, stat(p, &st) == 0 && S_ISDIR(st.st_mode));
    return 1;
}

static int l_mkdirp(lua_State *L) {
    lua_pushboolean(L, mkdir_p(luaL_checkstring(L, 1)) == 0);
    return 1;
}

static int l_rmrf(lua_State *L) {
    lua_pushboolean(L, rm_rf(luaL_checkstring(L, 1)) == 0);
    return 1;
}

static int l_copy_file(lua_State *L) {
    const char *src = luaL_checkstring(L, 1);
    const char *dst = luaL_checkstring(L, 2);
    /* ensure parent dir exists */
    char tmp[4096];
    snprintf(tmp, sizeof tmp, "%s", dst);
    char *slash = strrchr(tmp, '/');
    if (slash) { *slash = '\0'; mkdir_p(tmp); }
    lua_pushboolean(L, copy_file_native(src, dst) == 0);
    return 1;
}

static int l_mkdtemp(lua_State *L) {
    const char *tmpdir = getenv("TMPDIR");
    char tmpl[4096];
    snprintf(tmpl, sizeof tmpl, "%s/cdeps-XXXXXX", (tmpdir && *tmpdir) ? tmpdir : "/tmp");
    char *res = mkdtemp(tmpl);
    if (!res) { lua_pushnil(L); return 1; }
    lua_pushstring(L, res);
    return 1;
}

static int l_walk(lua_State *L) {
    const char *base = luaL_checkstring(L, 1);
    lua_newtable(L);
    int idx = 0;
    walk_into(L, base, "", &idx);
    return 1;
}

static const luaL_Reg cdeps_native_lib[] = {
    {"sha256",    l_sha256},
    {"exists",    l_exists},
    {"isdir",     l_isdir},
    {"mkdirp",    l_mkdirp},
    {"rmrf",      l_rmrf},
    {"copy_file", l_copy_file},
    {"mkdtemp",   l_mkdtemp},
    {"walk",      l_walk},
    {NULL, NULL}
};

static int luaopen_cdeps_native(lua_State *L) {
    luaL_newlib(L, cdeps_native_lib);
    return 1;
}

/* --------------------------------------------------------------------------
 * Driver
 * ------------------------------------------------------------------------ */

/* Build the standard `arg` table so cdeps.lua dispatches the same as under a
 * stock lua interpreter: arg[0] = program, arg[1..] = command-line args. */
static void set_arg_table(lua_State *L, int argc, char **argv) {
    lua_newtable(L);
    for (int i = 0; i < argc; i++) {
        lua_pushstring(L, argv[i]);
        lua_rawseti(L, -2, i);
    }
    lua_setglobal(L, "arg");
}

static int load_logic(lua_State *L) {
    /* Dev override: load cdeps.lua from disk so the C shell needn't be rebuilt
     * for logic changes (PLAN: CDEPS_DEV / sibling file). */
    const char *dev = getenv("CDEPS_DEV");
    const char *path = getenv("CDEPS_LUA");
    if (!path && dev) path = "cdeps.lua";
    if (path) {
        if (luaL_loadfile(L, path) != LUA_OK) return LUA_ERRRUN;
        return LUA_OK;
    }
#ifdef CDEPS_HAVE_BYTECODE
    return luaL_loadbuffer(L, (const char *)cdeps_luac_data, cdeps_luac_len, "@cdeps.lua");
#else
    /* No embedded bytecode (built without the generated header): fall back to
     * the sibling cdeps.lua so the binary is still usable. */
    return luaL_loadfile(L, "cdeps.lua");
#endif
}

int main(int argc, char **argv) {
    lua_State *L = luaL_newstate();
    luaL_openlibs(L);

    /* register the native module on package.preload so require() finds it */
    luaL_requiref(L, "cdeps_native", luaopen_cdeps_native, 0);
    lua_pop(L, 1);

    set_arg_table(L, argc, argv);

    if (load_logic(L) != LUA_OK) {
        fprintf(stderr, "cdeps: %s\n", lua_tostring(L, -1));
        lua_close(L);
        return 1;
    }
    if (lua_pcall(L, 0, 0, 0) != LUA_OK) {
        fprintf(stderr, "cdeps: %s\n", lua_tostring(L, -1));
        lua_close(L);
        return 1;
    }
    lua_close(L);
    return 0;
}
