# cdeps — thin C shell + embedded Lua (vendored under deps/lua-5.5.0).
#
# Build: `make`           -> ./cdeps  (embeds bytecode-compiled cdeps.lua)
# Dev:   `CDEPS_DEV=1 ./cdeps ...`     (loads cdeps.lua from disk; no rebuild)
# or:    `lua cdeps.lua ...`           (system lua, shell-based fallbacks)

LUA_DIR  := deps/lua-5.5.0/src
LUA_SRCS := $(filter-out $(LUA_DIR)/lua.c $(LUA_DIR)/luac.c,$(wildcard $(LUA_DIR)/*.c))
LUA_OBJS := $(LUA_SRCS:.c=.o)

CC      ?= cc
CFLAGS  ?= -O2 -Wall
CFLAGS  += -std=c99
LIBS    := -lm

PREFIX  ?= /usr/local

# Always build against the VENDORED Lua under deps/ — never the system Lua.
# We compile + link the Lua sources in $(LUA_DIR) directly (never -llua), and
# pass this include path FIRST (ahead of an overridable CFLAGS / any CPATH) so
# a system lua.h can never shadow the vendored one and cause an ABI mismatch.
LUA_INC := -I$(LUA_DIR)

UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
  CFLAGS += -DLUA_USE_MACOSX
else
  CFLAGS += -DLUA_USE_LINUX
  LIBS   += -ldl
endif

.PHONY: all clean test
all: cdeps

cdeps: cdeps.o $(LUA_OBJS)
	$(CC) $(CFLAGS) -o $@ cdeps.o $(LUA_OBJS) $(LIBS)

# main.c #includes the generated bytecode header.
cdeps.o: main.c sha256.h cdeps_luac.h
	$(CC) $(LUA_INC) $(CFLAGS) -c -o $@ main.c

# luac built from the vendored Lua source, used to precompile cdeps.lua.
luac: $(LUA_OBJS) $(LUA_DIR)/luac.o
	$(CC) $(CFLAGS) -o $@ $(LUA_OBJS) $(LUA_DIR)/luac.o $(LIBS)

# embed cdeps.lua as bytecode via bin2c (symbols: cdeps_luac_data + _len).
bin2c: bin2c.c
	$(CC) $(CFLAGS) -o $@ bin2c.c

cdeps_luac.h: cdeps.lua luac bin2c
	./luac -o cdeps.luac cdeps.lua
	./bin2c cdeps.luac $@ cdeps_luac
	rm -f cdeps.luac

# Builds the vendored Lua objects (and luac.o). LUA_INC keeps them on the
# vendored headers even if the source is ever moved out of its own dir.
%.o: %.c
	$(CC) $(LUA_INC) $(CFLAGS) -c -o $@ $<

install: cdeps
	cp cdeps $(PREFIX)/bin/

test: cdeps
	./test.sh

clean:
	rm -f cdeps cdeps.o luac bin2c cdeps.luac $(LUA_OBJS) $(LUA_DIR)/luac.o
