# cdeps — thin C shell + embedded Lua (vendored under deps/lua-5.5.0).
#
# Build: `make`           -> ./cdeps  (embeds bytecode-compiled cdeps.lua)
# Dev:   `CDEPS_DEV=1 ./cdeps ...`     (loads cdeps.lua from disk; no rebuild)
# or:    `lua cdeps.lua ...`           (system lua, shell-based fallbacks)

LUA_DIR  := deps/lua-5.5.0/src
LUA_SRCS := $(filter-out $(LUA_DIR)/lua.c $(LUA_DIR)/luac.c,$(wildcard $(LUA_DIR)/*.c))
LUA_OBJS := $(LUA_SRCS:.c=.o)

CC      ?= cc
CFLAGS  ?= -O2 -Wall
CFLAGS  += -std=c99 -I$(LUA_DIR)
LIBS    := -lm

UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
  CFLAGS += -DLUA_USE_MACOSX
else
  CFLAGS += -DLUA_USE_LINUX
  LIBS   += -ldl
endif

.PHONY: all clean test
all: cdeps

cdeps: cdeps.o $(LUA_OBJS)
	$(CC) $(CFLAGS) -o $@ cdeps.o $(LUA_OBJS) $(LIBS)

# cdeps.c #includes the generated bytecode header.
cdeps.o: cdeps.c sha256.h cdeps_lua.h
	$(CC) $(CFLAGS) -c -o $@ cdeps.c

# luac built from the vendored Lua source, used to precompile cdeps.lua.
luac: $(LUA_OBJS) $(LUA_DIR)/luac.o
	$(CC) $(CFLAGS) -o $@ $(LUA_OBJS) $(LUA_DIR)/luac.o $(LIBS)

# embed cdeps.lua as bytecode via bin2c (symbols: cdeps_luac_data + _len).
bin2c: bin2c.c
	$(CC) $(CFLAGS) -o $@ bin2c.c

cdeps_lua.h: cdeps.lua luac bin2c
	./luac -o cdeps.luac cdeps.lua
	./bin2c cdeps.luac $@ cdeps_luac
	rm -f cdeps.luac

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

test: cdeps
	./test.sh

clean:
	rm -f cdeps cdeps.o luac bin2c cdeps_lua.h cdeps.luac $(LUA_OBJS) $(LUA_DIR)/luac.o
